name: 'Setup qemu emulation'
description: 'Setup emulation of another CPU'
author: 'Damian Mee <spam@meedamian.com>'
inputs: 
  target-arch:
    description: 'Architecture to be emulated.  Examples: arm, arm64'
    required: true
    default: 'arm'
runs:
  using: 'docker'
  image: 'docker://meedamian/simple-qemu-test:latest'
  args:
#    - ${{ inputs.targetArchitecture }}
    - '--reset'
    - '-p yes'
branding:
  color: 'green'
  icon: 'target'
